---
title: "Final Project2"
author: "Marinela Inguito"
format: 
    html: 
        toc: true
    pdf: default
editor: visual
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(caret)
library(GGally)
library(mlbench)
library(ggplot2)
library(patchwork)
library(corrplot)

library(RANN) 
library(nnet) 
library(class)
library(e1071)
library(kernlab)
library(gt)
library(randomForest)
library(earth)
library(tibble)
library(dplyr)
library(AppliedPredictiveModeling)
library(readr)
# Set ggplot
theme_set(theme_minimal())
```

```{r}
# Load the dataset
osteo_df <- read_csv("osteoporosis.csv", show_col_types = FALSE)
```

```{r}
print((osteo_df))
```

```{r}
# Display the data types of each column
data_types <- sapply(osteo_df, class)
for (col_name in names(data_types)) {
  cat(paste(col_name, ":", data_types[col_name], "\n"))
}
```

```{r}
# Print the data frame
colSums(is.na(osteo_df))
```

```{r}
str(osteo_df)
```

```{r}
#  Convert variables to factor
#osteo_df$Osteoporosis <- as.factor(osteo_df$Osteoporosis)
osteo_df <- osteo_df |>
  mutate_if(is.character, as.factor)

# View the encoded data frame
str(osteo_df)
```

```{r}
set.seed(123)
# Define target and predictors
predictors <- osteo_df[, -16]
response <- osteo_df[, 16]

# Split the data into training and test sets
osteo_index <- createDataPartition(response, p = 0.8, list = FALSE)
predictors_train <- predictors[osteo_index, ]
predictors_test <- predictors[-osteo_index, ]
response_train <- response[osteo_index]
response_test <- response[-osteo_index]
```
