---
title: "Final Project KM"
output: html_document
date: "2024-06-06"
---

```{r}
# Import Packages 
library(dplyr)
library(tidyr)
library(ggplot2)
library(pROC)
library(caret)
```

### EDA 

```{r}
osteo_df <- as.data.frame(osteoporosis)
head(osteo_df)
```

```{r}
# Structure of Dataset 
str(osteo_df)
```

```{r}
# Change character variables to factors 
osteo_df <- osteo_df |>
  mutate_if(is.character, as.factor)
```


```{r}
# Change outcome variable to factor
osteo_df$Osteoporosis <- as.factor(osteo_df$Osteoporosis)
```

```{r}
# Structure of Dataset after Mutate
str(osteo_df)
```

```{r}
tail(osteo_df)
```


```{r}
# Missing Data - There is no missing data 
colSums(is.na(osteo_df))
```


```{r}
# Summary of Age Column (Integer)
summary(osteo_df$Age)
```
```{r}
ggplot(osteo_df, aes(x = Age)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Age", x = "Age", y = "Frequency") +
  theme_minimal()
```


```{r}
# Frequency for Categorical Variables (as Factors) 
df_long <- osteo_df |>
    pivot_longer(!c(Id, Age), names_to = "Variable", values_to = "Value")

# Create the plot
ggplot(df_long, aes(x = Value, fill = Variable)) + 
  geom_bar(show.legend = FALSE) + 
  facet_wrap(~ Variable, scales = "free", ncol = 4) + 
  labs(title = "Frequency of Categorical Variables", x = "Category", y = "Frequency") +
  theme_minimal()

```
```{r}
# Checking for duplicates
duplicated_rows <- duplicated(osteo_df)

# Number of duplicate rows
num_duplicates <- sum(duplicated_rows)

# Print duplicate rows
duplicate_rows <- osteo_df[duplicated_rows, ]
duplicate_rows
```

```{r}
# Check for Correlation with categorical variables and outcome variables 
cols_to_analyze <- setdiff(names(osteo_df), c("Age", "Id", "Osteoporosis"))

# Perform chi-square test for each column
results <- lapply(cols_to_analyze, function(col) {
  chisq_test <- chisq.test(table(osteo_df[[col]], osteo_df$Osteoporosis))
  return(chisq_test)
})

# Print the results
for (i in seq_along(cols_to_analyze)) {
  cat("Chi-square test for", cols_to_analyze[i], ":\n")
  print(results[[i]])
  cat("\n")
}

```


### PreProcessing 


```{r}
predictors <- osteo_df[, 2:(ncol(osteo_df) - 1)]
response <- osteo_df[, ncol(osteo_df)]
```

```{r}
set.seed(503)
# Split the data into training and test sets
osteo_index <- createDataPartition(response, p = 0.8, list = FALSE)
```

```{r}

predictors_train <- predictors[osteo_index, ]
predictors_test <- predictors[-osteo_index, ]
yield_train <- response[osteo_index ]
yield_test <- response[-osteo_index ]
```

```{r}
# Change factors to numeric for LDA 
predictors_train <- data.frame(lapply(predictors_train, function(x) {
  if (is.factor(x)) as.numeric(x) else x
}))
```

```{r}
# Change factors to numeric for LDA 
predictors_test <- data.frame(lapply(predictors_test, function(x) {
  if (is.factor(x)) as.numeric(x) else x
}))
```

```{r}
# Check for missing data 
sum(is.na(predictors_train)) 
```
```{r}
# Check for missing data 
sum(is.na(predictors_test)) 
```

### Modeling 

```{r}
levels(yield_train) <- make.names(levels(yield_train))
levels(yield_test) <- make.names(levels(yield_test))

ctrl <- trainControl(method = "cv", 
                    summaryFunction = twoClassSummary,
                    classProbs = TRUE,
                    savePredictions = TRUE)
```



```{r}
set.seed(503)
# Fit logistic regression model
log_model <- train(x = predictors_train,
    y = yield_train,
    method = "glm",
    preProcess = c("center", "scale"),
    metric = "ROC",
    trControl = ctrl)

# Summary of the model
summary(log_model)
```

```{r}
Log_CM <- confusionMatrix(log_model, norm = "none")
Log_CM
```
```{r}
Log_predictions <- predict(log_model, newdata = predictors_test, type = "prob")
Log_probs <- Log_predictions[, "X1"]
```


```{r}
roc_obj_log <- roc(yield_test, Log_probs)

# Plot the ROC curve
plot(roc_obj_log, main = "ROC Curve for Log Model")

# Add AUC to the plot
auc(roc_obj_log)
```



```{r}
#LDA 
set.seed(503)
LDA_model <- train(x = predictors_train,
    y = yield_train,
    method = "lda",
    metric = "ROC",
    preProcess = c("center", "scale"),
    trControl = ctrl)
```


```{r}
LDA_CM <- confusionMatrix(LDA_model, norm = "none")
LDA_CM
```
```{r}
LDA_predictions <- predict(LDA_model, newdata = predictors_test, type = "prob")
LDA_probs <- LDA_predictions[, "X1"]
```


```{r}
LDA_roc_obj <- roc(yield_test, LDA_probs)

# Plot the ROC curve
plot(LDA_roc_obj, main = "ROC Curve for LDA Model")

# Add AUC to the plot
auc(LDA_roc_obj)
```


```{r}
# Penalized Model 
glmnGrid <- expand.grid(alpha = c(0, .1, .2, .4, .6, .8, 1),
lambda = seq(.01, .2, length = 10))

set.seed(503)

Penalized_model <- train(x = predictors_train,
    y = yield_train,
    method = "glmnet",
    tuneGrid = glmnGrid,
    metric = "ROC",
    trControl = ctrl)
```


```{r}
Penalized_CM <- confusionMatrix(Penalized_model, norm = "none")
Penalized_CM
```
```{r}
penalized_predictions <- predict(Penalized_model, newdata = predictors_test, type = "prob")
penalized_probs <- penalized_predictions[, "X1"]
```


```{r}
penalized_roc_obj <- roc(yield_test, penalized_probs)

# Plot the ROC curve
plot(penalized_roc_obj, main = "ROC Curve for Penalized Model")

# Add AUC to the plot
auc(penalized_roc_obj)
```




```{r}
# Nearest Shrunken Centroid
set.seed(503)
nsc_model <- train(x = predictors_train,
    y = yield_train,
    method = "pam",
    preProc = c("center", "scale"),
    tuneGrid = data.frame(threshold = seq(0, 25, length = 30)),
    metric = "ROC",
    trControl = ctrl)

```
```{r}
nsc_CM <- confusionMatrix(nsc_model, norm = "none")
nsc_CM
```
```{r}
nsc_predictions <- predict(nsc_model, newdata = predictors_test, type = "prob")
nsc_probs <- nsc_predictions[, "X1"]
```

```{r}
nsc_roc_obj <- roc(yield_test, nsc_probs)

# Plot the ROC curve
plot(nsc_roc_obj, main = "ROC Curve for Nsc Model")

# Add AUC to the plot
auc(nsc_roc_obj)
```


```{r} 
# Neural Net
set.seed(503)
nn_grid <- expand.grid(decay = c(0, 0.01, 0.1), size = 1:10)

neuralnet <- train(x = predictors_train,
                       y = yield_train,
                       method = "nnet",
                       tuneGrid =  nn_grid,
                       preProc = c("center", "scale"),
                       trControl = ctrl,  
                       metric = "ROC",
                       linout = FALSE, trace = FALSE, maxit = 500)
```

```{r}
neural_CM <- confusionMatrix(neuralnet, norm = "none")
neural_CM
```

```{r}
neuralnet
```


```{r}
net_predictions <- predict(neuralnet, newdata = predictors_test, type = "prob")
net_probs <- net_predictions[, "X1"]
```


```{r}
net_roc_obj <- roc(yield_test, net_probs)

# Plot the ROC curve
plot(net_roc_obj, main = "ROC Curve for Neural Net Model")

# Add AUC to the plot
auc(net_roc_obj)
```


```{r}
# SVM model
svm_grid <- expand.grid(sigma = c(0.01, 0.1, 1), 
                        C = c(0.1, 1, 10))

set.seed(503)

svm <- train(x = predictors_train,
                   y = yield_train,
                   method = "svmRadial", 
                   preProc = c("center", "scale"),
                   trControl = ctrl,  
                   metric = "ROC",
                   tuneGrid = svm_grid)


```

```{r}
svm_predictions <- predict(svm, newdata = predictors_test, type = "prob")
svm_probs <- svm_predictions[, "X1"]
```


```{r}
svm_roc_obj <- roc(yield_test, svm_probs)

# Plot the ROC curve
plot(svm_roc_obj, main = "ROC Curve for SVM Model")

# Add AUC to the plot
auc(svm_roc_obj)
```



